package com.candbright.quiz.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.candbright.quiz.model.data.Question;
import com.candbright.quiz.model.data.QuestionBank;

import com.candbright.quiz.dao.QuestionDao;
import com.candbright.quiz.dao.QuestionBankDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig questionDaoConfig;
    private final DaoConfig questionBankDaoConfig;

    private final QuestionDao questionDao;
    private final QuestionBankDao questionBankDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        questionBankDaoConfig = daoConfigMap.get(QuestionBankDao.class).clone();
        questionBankDaoConfig.initIdentityScope(type);

        questionDao = new QuestionDao(questionDaoConfig, this);
        questionBankDao = new QuestionBankDao(questionBankDaoConfig, this);

        registerDao(Question.class, questionDao);
        registerDao(QuestionBank.class, questionBankDao);
    }

    public void clear() {
        questionDaoConfig.clearIdentityScope();
        questionBankDaoConfig.clearIdentityScope();
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public QuestionBankDao getQuestionBankDao() {
        return questionBankDao;
    }

}
